[phases.setup]
nixPkgs = ["nodejs-20_x", "python39", "pip"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

