[phases.setup]
nixPkgs = ["nodejs-20_x", "python39", "pip"]

[phases.install]
cmds = [
  "corepack enable",
  "pnpm install",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm start"

